# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karel Štogl
email: info@karelstogl.cz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://www.karelstogl.cz" # the base hostname & protocol for your site
twitter_username: karelstogl
github_username:  jerrylabs

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock

sass:
    style: compressed

permalink: /aktuality/:title.html
collections:
#  program:
#    output: true
#    permalink: /program/:path/

defaults:   # defaults values for collection scope
#  -
#    scope:
#      path: "_program"
#    values:
#      layout: "page"
#      rbar: "program"

emptyArray: []
exclude: [vendor]
